### PR TITLE
Add /r/SwanseaCity and text clean up

### PR DESCRIPTION
**Pull request by jimmithy**
Added /r/swanseacity to the approved subs list (I'm a mod there) and ^did ^some ^small ^text ^clean ^up.

Keep up the great work!

### CODE REVIEW

**Comment by ZacSweers** [comment]
Looks good, can you just send me a message on reddit so I can confirm you're a mod? www.reddit.com/u/pandanomic :)

**Comment by jimmithy** [comment]
Sent from the mod account, so I'd recommend not replying to that message because everyone else on the team will receive it. If you do want to though, I have the same username in both places :+1:

**Comment by ZacSweers** [comment]
Confirmed, thanks!

**Comment by ZacSweers** [comment]
Updated heroku as well, so should see it start appearing on /r/swanseacity now :)

**Pull request merged**
